apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: insurance-management-prod
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@insurance-management-postgres.insurance-management-prod.svc.cluster.local:5432/insurance_management"
  JWT_SECRET: "123"
  NOTIFICATIONS_API_URL: ""
  NOTIFICATIONS_JWT_SECRET: ""
  RESET_PASSWORD_URL: ""
