apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: insurance-management-homolog
type: Opaque
stringData:
  DATABASE_URL: ""
  JWT_SECRET: ""
  NOTIFICATIONS_API_URL: ""
  NOTIFICATIONS_JWT_SECRET: ""
  RESET_PASSWORD_URL: ""
