apiVersion: v1
kind: Service
metadata:
  name: insurance-management-postgres
  namespace: insurance-management-prod
spec:
  type: ClusterIP
  selector:
    app: insurance-management-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
