apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: insurance-management-homolog
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "insurance_management"
